[platformio]
default_envs = cyd_esp32_ota

[env]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_port = COM11

lib_deps =
  lvgl/lvgl@^8.3.11
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^6.21.4

build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TOUCH_CS=33
  -D TOUCH_CLK=25
  -D TOUCH_DIN=32
  -D TOUCH_DOUT=39
  -D TOUCH_IRQ=36
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D PENDANT_DISPLAY_TEST=0
  -D PENDANT_RP_LINK_ENABLE=1
  -D PENDANT_RP_LINK_TX_ENABLE=0
  -D PENDANT_REAL_JOG_ENABLE=1
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_FONT6=1
  -D LOAD_FONT7=1
  -D LOAD_FONT8=1
  -D SMOOTH_FONT=1
  -D SPI_FREQUENCY=40000000


[env:cyd_esp32_usb]
upload_protocol = esptool
upload_port = COM11
monitor_port = COM11


[env:cyd_esp32_ota]
upload_protocol = espota
upload_port = 192.168.0.177
monitor_port = COM11
