; RP2040 firmware for the Carvera CYD pendant input co-processor.

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
build_flags =
  -D RP_CYD_UART_ENABLE=1
  -D RP_CYD_UART_TX_ENABLE=1
  -D RP_CYD_UART_RX_ENABLE=1
  -D RP_DEBUG_MPG_SERIAL=0
